name: boygiene
description: "A hygiene reminder app for kids"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_local_notifications: ^16.3.3
  provider: ^6.1.1
  shared_preferences: ^2.0.15
  intl: ^0.19.0
  timezone: ^0.9.4
  google_fonts: ^6.2.1
  confetti: ^0.7.0
  table_calendar: ^3.1.2
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - assets/ # Declare the assets folder

  # An image asset can refer to one or more resolution-specific "variants", see 